// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMFkCLE_s0-xgGIeOnTFw2bbY3Ha0DcpM',
    appId: '1:589232610494:web:cd3ae166b9df86deae52ef',
    messagingSenderId: '589232610494',
    projectId: 'travel-buddy-a7cba',
    authDomain: 'travel-buddy-a7cba.firebaseapp.com',
    storageBucket: 'travel-buddy-a7cba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCpcwOh29hq3O5DP0kYlA1oyP12ZF7BJg',
    appId: '1:589232610494:android:a551223fc23f0645ae52ef',
    messagingSenderId: '589232610494',
    projectId: 'travel-buddy-a7cba',
    storageBucket: 'travel-buddy-a7cba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSEBuY61_8IwpHn1yu1vCx42h8Z3AZoyA',
    appId: '1:589232610494:ios:fc6e1d8b40d36850ae52ef',
    messagingSenderId: '589232610494',
    projectId: 'travel-buddy-a7cba',
    storageBucket: 'travel-buddy-a7cba.firebasestorage.app',
    iosBundleId: 'com.jetravelplus.travelbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSEBuY61_8IwpHn1yu1vCx42h8Z3AZoyA',
    appId: '1:589232610494:ios:fc6e1d8b40d36850ae52ef',
    messagingSenderId: '589232610494',
    projectId: 'travel-buddy-a7cba',
    storageBucket: 'travel-buddy-a7cba.firebasestorage.app',
    iosBundleId: 'com.jetravelplus.travelbuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMFkCLE_s0-xgGIeOnTFw2bbY3Ha0DcpM',
    appId: '1:589232610494:web:4e688036b98565c2ae52ef',
    messagingSenderId: '589232610494',
    projectId: 'travel-buddy-a7cba',
    authDomain: 'travel-buddy-a7cba.firebaseapp.com',
    storageBucket: 'travel-buddy-a7cba.firebasestorage.app',
  );
}
